# Generated by Django 6.0.2 on 2026-03-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key_storage',
            name='files',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
